"""remove_unique_email_from_profesores

Revision ID: 0bc6b3d6909d
Revises: bbb079905314
Create Date: 2026-05-21 22:09:26.431571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc6b3d6909d'
down_revision: Union[str, None] = 'bbb079905314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profesores_email'), table_name='profesores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profesores_email'), 'profesores', ['email'], unique=True)
    # ### end Alembic commands ###
