"""drop_cupo_oculto_from_clase_instancias

Revision ID: 446ff3dfa3c2
Revises: b2c3d4e5f6a7
Create Date: 2026-05-19 03:12:37.692424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446ff3dfa3c2'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clase_instancias', 'cupo_oculto')
    op.alter_column('suscripciones', 'clase_template_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suscripciones', 'clase_template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('clase_instancias', sa.Column('cupo_oculto', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
