from enum import Enum

class Role(str, Enum):
    ROLE_ADMIN = "ROLE_ADMIN"
    ROLE_RECEPTION = "ROLE_RECEPTION"
    ROLE_CLIENT = "ROLE_CLIENT"
    ROLE_USER_LIST = "ROLE_USER_LIST"
    ROLE_USER_CREATE = "ROLE_USER_CREATE"
    ROLE_USER_UPDATE = "ROLE_USER_UPDATE"
    ROLE_USER_DELETE = "ROLE_USER_DELETE"
    
role_hierarchy = {
    "ADMIN": [Role.ROLE_ADMIN, Role.ROLE_RECEPTION, Role.ROLE_CLIENT, Role.ROLE_USER_LIST, Role.ROLE_USER_CREATE, Role.ROLE_USER_UPDATE, Role.ROLE_USER_DELETE],
    "RECEPTION": [Role.ROLE_RECEPTION, Role.ROLE_CLIENT, Role.ROLE_USER_LIST, Role.ROLE_USER_CREATE, Role.ROLE_USER_UPDATE, Role.ROLE_USER_DELETE],
    "CLIENT": [Role.ROLE_CLIENT],
}