from enum import Enum

class Role(str, Enum):
    ROLE_ADMIN = "ROLE_ADMIN"
    ROLE_RECEPCION = "ROLE_RECEPCION"
    ROLE_CLIENT = "ROLE_CLIENT"
    ROLE_USER_LIST = "ROLE_USER_LIST"
    ROLE_USER_CREATE = "ROLE_USER_CREATE"
    ROLE_USER_UPDATE = "ROLE_USER_UPDATE"
    ROLE_USER_DELETE = "ROLE_USER_DELETE"
    ROLE_PROFESOR_LIST = "ROLE_PROFESOR_LIST"
    ROLE_PROFESOR_CREATE = "ROLE_PROFESOR_CREATE"
    ROLE_PROFESOR_UPDATE = "ROLE_PROFESOR_UPDATE"
    ROLE_PROFESOR_DELETE = "ROLE_PROFESOR_DELETE"
    ROLE_CLASE_CREATE = "ROLE_CLASE_CREATE"
    ROLE_CLASE_UPDATE = "ROLE_CLASE_UPDATE"
    ROLE_CLASE_DELETE = "ROLE_CLASE_DELETE"
    ROLE_SALA_LIST = "ROLE_SALA_LIST"

role_hierarchy = {
    "ADMIN": [
        Role.ROLE_ADMIN, Role.ROLE_RECEPCION, Role.ROLE_CLIENT,
        Role.ROLE_USER_LIST, Role.ROLE_USER_CREATE, Role.ROLE_USER_UPDATE, Role.ROLE_USER_DELETE,
        Role.ROLE_PROFESOR_LIST, Role.ROLE_PROFESOR_CREATE, Role.ROLE_PROFESOR_UPDATE, Role.ROLE_PROFESOR_DELETE,
        Role.ROLE_CLASE_CREATE, Role.ROLE_CLASE_UPDATE, Role.ROLE_CLASE_DELETE, Role.ROLE_SALA_LIST,
    ],
    "RECEPCION": [
        Role.ROLE_RECEPCION, Role.ROLE_CLIENT,
        Role.ROLE_USER_LIST, Role.ROLE_USER_CREATE, Role.ROLE_USER_UPDATE, Role.ROLE_USER_DELETE,
        Role.ROLE_PROFESOR_LIST, Role.ROLE_PROFESOR_CREATE, Role.ROLE_PROFESOR_UPDATE, Role.ROLE_PROFESOR_DELETE,
        Role.ROLE_CLASE_CREATE, Role.ROLE_CLASE_UPDATE, Role.ROLE_CLASE_DELETE, Role.ROLE_SALA_LIST,
    ],
    "CLIENT": [Role.ROLE_CLIENT],
    "CLIENTE": [Role.ROLE_CLIENT],
}
